// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: feature_flags.proto

package feature_flags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlagName string `protobuf:"bytes,1,opt,name=flagName,proto3" json:"flagName,omitempty"`
}

func (x *FeatureFlagRequest) Reset() {
	*x = FeatureFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feature_flags_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureFlagRequest) ProtoMessage() {}

func (x *FeatureFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flags_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureFlagRequest.ProtoReflect.Descriptor instead.
func (*FeatureFlagRequest) Descriptor() ([]byte, []int) {
	return file_feature_flags_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureFlagRequest) GetFlagName() string {
	if x != nil {
		return x.FlagName
	}
	return ""
}

type FeatureFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlagValue string `protobuf:"bytes,1,opt,name=flagValue,proto3" json:"flagValue,omitempty"`
}

func (x *FeatureFlagResponse) Reset() {
	*x = FeatureFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feature_flags_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureFlagResponse) ProtoMessage() {}

func (x *FeatureFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flags_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureFlagResponse.ProtoReflect.Descriptor instead.
func (*FeatureFlagResponse) Descriptor() ([]byte, []int) {
	return file_feature_flags_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureFlagResponse) GetFlagValue() string {
	if x != nil {
		return x.FlagValue
	}
	return ""
}

var File_feature_flags_proto protoreflect.FileDescriptor

var file_feature_flags_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x12,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6c, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6c, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x33,
	0x0a, 0x13, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6c, 0x61, 0x67, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6c, 0x61, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x32, 0x60, 0x0a, 0x13, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x46, 0x6c,
	0x61, 0x67, 0x73, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x12, 0x49, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x46, 0x6c, 0x61, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6b, 0x6b, 0x69, 0x6e, 0x6f, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2d, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x3b, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_feature_flags_proto_rawDescOnce sync.Once
	file_feature_flags_proto_rawDescData = file_feature_flags_proto_rawDesc
)

func file_feature_flags_proto_rawDescGZIP() []byte {
	file_feature_flags_proto_rawDescOnce.Do(func() {
		file_feature_flags_proto_rawDescData = protoimpl.X.CompressGZIP(file_feature_flags_proto_rawDescData)
	})
	return file_feature_flags_proto_rawDescData
}

var file_feature_flags_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_feature_flags_proto_goTypes = []interface{}{
	(*FeatureFlagRequest)(nil),  // 0: proto.FeatureFlagRequest
	(*FeatureFlagResponse)(nil), // 1: proto.FeatureFlagResponse
}
var file_feature_flags_proto_depIdxs = []int32{
	0, // 0: proto.FeatureFlagsSidecar.GetFeatureFlag:input_type -> proto.FeatureFlagRequest
	1, // 1: proto.FeatureFlagsSidecar.GetFeatureFlag:output_type -> proto.FeatureFlagResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feature_flags_proto_init() }
func file_feature_flags_proto_init() {
	if File_feature_flags_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feature_flags_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feature_flags_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feature_flags_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feature_flags_proto_goTypes,
		DependencyIndexes: file_feature_flags_proto_depIdxs,
		MessageInfos:      file_feature_flags_proto_msgTypes,
	}.Build()
	File_feature_flags_proto = out.File
	file_feature_flags_proto_rawDesc = nil
	file_feature_flags_proto_goTypes = nil
	file_feature_flags_proto_depIdxs = nil
}
