// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package feature_flags

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FeatureFlagsSidecarClient is the client API for FeatureFlagsSidecar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeatureFlagsSidecarClient interface {
	GetFeatureFlag(ctx context.Context, in *FeatureFlagRequest, opts ...grpc.CallOption) (*FeatureFlagResponse, error)
}

type featureFlagsSidecarClient struct {
	cc grpc.ClientConnInterface
}

func NewFeatureFlagsSidecarClient(cc grpc.ClientConnInterface) FeatureFlagsSidecarClient {
	return &featureFlagsSidecarClient{cc}
}

func (c *featureFlagsSidecarClient) GetFeatureFlag(ctx context.Context, in *FeatureFlagRequest, opts ...grpc.CallOption) (*FeatureFlagResponse, error) {
	out := new(FeatureFlagResponse)
	err := c.cc.Invoke(ctx, "/proto.FeatureFlagsSidecar/GetFeatureFlag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeatureFlagsSidecarServer is the server API for FeatureFlagsSidecar service.
// All implementations must embed UnimplementedFeatureFlagsSidecarServer
// for forward compatibility
type FeatureFlagsSidecarServer interface {
	GetFeatureFlag(context.Context, *FeatureFlagRequest) (*FeatureFlagResponse, error)
	mustEmbedUnimplementedFeatureFlagsSidecarServer()
}

// UnimplementedFeatureFlagsSidecarServer must be embedded to have forward compatible implementations.
type UnimplementedFeatureFlagsSidecarServer struct {
}

func (UnimplementedFeatureFlagsSidecarServer) GetFeatureFlag(context.Context, *FeatureFlagRequest) (*FeatureFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeatureFlag not implemented")
}
func (UnimplementedFeatureFlagsSidecarServer) mustEmbedUnimplementedFeatureFlagsSidecarServer() {}

// UnsafeFeatureFlagsSidecarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeatureFlagsSidecarServer will
// result in compilation errors.
type UnsafeFeatureFlagsSidecarServer interface {
	mustEmbedUnimplementedFeatureFlagsSidecarServer()
}

func RegisterFeatureFlagsSidecarServer(s grpc.ServiceRegistrar, srv FeatureFlagsSidecarServer) {
	s.RegisterService(&FeatureFlagsSidecar_ServiceDesc, srv)
}

func _FeatureFlagsSidecar_GetFeatureFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureFlagsSidecarServer).GetFeatureFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FeatureFlagsSidecar/GetFeatureFlag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureFlagsSidecarServer).GetFeatureFlag(ctx, req.(*FeatureFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeatureFlagsSidecar_ServiceDesc is the grpc.ServiceDesc for FeatureFlagsSidecar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeatureFlagsSidecar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FeatureFlagsSidecar",
	HandlerType: (*FeatureFlagsSidecarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeatureFlag",
			Handler:    _FeatureFlagsSidecar_GetFeatureFlag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feature_flags.proto",
}
